name: Tamingplus
version: 1.0-SNAPSHOT
main: devlaunchers.tamingplus.Tamingplus
api-version: 1.16
commands:
  giveTamingItem:
    description: Gives you a special taming item
    usage: /giveTamingItem 7 255
    permission: TamingPlus.giveTamingItem